from experiments.model_clients import ModelClient

from .belief_prompt import BeliefPromptBuyer
from .bayesian_belief_full_framework import BayesianBeliefFullFrameworkBuyer
from .continuous_solver.buyer import (
    ContinuousHybridEVBuyer,
    ContinuousHybridPromptPlannerBuyer,
    BayesianBeliefLLMPlannerBuyer,
    ContinuousRuleContextualCEMEVBuyer,
    ContinuousRuleCEMEVBuyer,
    ContinuousRuleConservativeEVBuyer,
    ContinuousRuleEVBuyer,
)
from .continuous_solver.identifiable_buyer import (
    ContinuousRuleActiveProbeBuyer,
    ContinuousRuleFrozenEVBuyer,
    ContinuousRuleRegimeMonitorBuyer,
)
from .counterfactual_response_belief import CounterfactualResponseBeliefBuyer
from .cot_prompt import CoTPromptBuyer
from .direct_prompt import DirectPromptBuyer
from .full_framework import FullFrameworkBuyer
from .planner_generator import PlannerGeneratorBuyer
from .price_policy_v03 import SmallPolicyBeliefV03Buyer, SmallPolicyV03Buyer
from .typed_belief import TypedBeliefBuyer
from .universal_framework import (
    UniversalFrameworkBuyer,
    UniversalFrameworkFrozenBuyer,
    UniversalFrameworkOracleBeliefBuyer,
    UniversalFrameworkV2Buyer,
    UniversalFrameworkV2FrozenBuyer,
    UniversalFrameworkV2OracleBeliefBuyer,
    UniversalFrameworkV2ShuffledBeliefBuyer,
    UniversalFrameworkV2WrongBeliefBuyer,
    UniversalFrameworkV3Buyer,
    UniversalFrameworkV3FrozenBuyer,
    UniversalFrameworkV3OracleBeliefBuyer,
    UniversalFrameworkV3ShuffledBeliefBuyer,
    UniversalFrameworkV3WrongBeliefBuyer,
    UniversalFrameworkV4Buyer,
    UniversalFrameworkV4FrozenBuyer,
    UniversalFrameworkV4OracleUtilityBuyer,
    UniversalFrameworkV4ShuffledFullBuyer,
    UniversalFrameworkV4WrongPolicyBuyer,
    UniversalFrameworkV5Buyer,
    UniversalFrameworkV5FrozenBuyer,
    UniversalFrameworkV5OracleUtilityBuyer,
    UniversalFrameworkV5ShuffledFullBuyer,
    UniversalFrameworkV5WrongPolicyBuyer,
    UniversalFrameworkV51Buyer,
    UniversalFrameworkV51FrozenBuyer,
    UniversalFrameworkV51OracleUtilityBuyer,
    UniversalFrameworkV51ShuffledFullBuyer,
    UniversalFrameworkV51WrongPolicyBuyer,
    UniversalFrameworkV52Buyer,
    UniversalFrameworkV52FrozenBuyer,
    UniversalFrameworkV52OracleUtilityBuyer,
    UniversalFrameworkV52ShuffledFullBuyer,
    UniversalFrameworkV52WrongPolicyBuyer,
    UniversalFrameworkV53Buyer,
    UniversalFrameworkV53FrozenBuyer,
    UniversalFrameworkV53OracleUtilityBuyer,
    UniversalFrameworkV53ShuffledFullBuyer,
    UniversalFrameworkV53WrongPolicyBuyer,
    UniversalFrameworkV54Buyer,
    UniversalFrameworkV54FrozenBuyer,
    UniversalFrameworkV54OracleUtilityBuyer,
    UniversalFrameworkV54ShuffledFullBuyer,
    UniversalFrameworkV54WrongPolicyBuyer,
    UniversalFrameworkV55Buyer,
    UniversalFrameworkV55FrozenBuyer,
    UniversalFrameworkV55NoFrontierBuyer,
    UniversalFrameworkV55OracleUtilityBuyer,
    UniversalFrameworkV55ShuffledFullBuyer,
    UniversalFrameworkV55WrongPolicyBuyer,
    UniversalFrameworkV56Buyer,
    UniversalFrameworkV56FrozenBuyer,
    UniversalFrameworkV56NoFrontierBuyer,
    UniversalFrameworkV56OracleUtilityBuyer,
    UniversalFrameworkV56ShuffledFullBuyer,
    UniversalFrameworkV56WrongPolicyBuyer,
    UniversalFrameworkV57Buyer,
    UniversalFrameworkV57FrozenBuyer,
    UniversalFrameworkV57NoFrontierBuyer,
    UniversalFrameworkV57OracleUtilityBuyer,
    UniversalFrameworkV57ShuffledFullBuyer,
    UniversalFrameworkV57ShuffledMixtureBuyer,
    UniversalFrameworkV57WrongPolicyBuyer,
    UniversalFrameworkV58Buyer,
    UniversalFrameworkV58FrozenBuyer,
    UniversalFrameworkV58NoFrontierBuyer,
    UniversalFrameworkV58OracleUtilityBuyer,
    UniversalFrameworkV58ShuffledFullBuyer,
    UniversalFrameworkV58WrongPolicyBuyer,
    UniversalFrameworkV59Buyer,
    UniversalFrameworkV59FrozenBuyer,
    UniversalFrameworkV59OracleUtilityBuyer,
    UniversalFrameworkV59ShuffledMixtureBuyer,
    UniversalFrameworkV59WrongPolicyBuyer,
    UniversalFrameworkV60Buyer,
    UniversalFrameworkV60FrozenBuyer,
    UniversalFrameworkV60NoAspirationPlannerBuyer,
    UniversalFrameworkV60OracleUtilityBuyer,
    UniversalFrameworkV60ShuffledMixtureBuyer,
    UniversalFrameworkV60WrongPolicyBuyer,
    UniversalFrameworkV61Buyer,
    UniversalFrameworkV61FrozenBuyer,
    UniversalFrameworkV61NoProbeBuyer,
    UniversalFrameworkV61OracleUtilityBuyer,
    UniversalFrameworkV61ShuffledMixtureBuyer,
    UniversalFrameworkV61WrongPolicyBuyer,
    UniversalFrameworkV62FinetunedPlannerBuyer,
    UniversalFrameworkV62UnguardedPlannerBuyer,
    UniversalFrameworkV63ConservativeAWRBuyer,
    UniversalFrameworkV64RewardLabeledLCBBuyer,
    UniversalFrameworkV65EvidenceGatedLCBBuyer,
    UniversalFrameworkShuffledBeliefBuyer,
    UniversalFrameworkWrongBeliefBuyer,
)


BUYER_CLASSES = {
    "direct_prompt": DirectPromptBuyer,
    "prompt_only": DirectPromptBuyer,
    "cot_prompt": CoTPromptBuyer,
    "belief_prompt": BeliefPromptBuyer,
    "belief_only": BeliefPromptBuyer,
    "full_framework": FullFrameworkBuyer,
    "planner_generator": PlannerGeneratorBuyer,
    "small_policy_v03": SmallPolicyV03Buyer,
    "price_policy_v03": SmallPolicyV03Buyer,
    "rl_price_policy_v03": SmallPolicyV03Buyer,
    "small_policy_belief_v03": SmallPolicyBeliefV03Buyer,
    "small_policy_v03_belief": SmallPolicyBeliefV03Buyer,
    "full_framework_small_policy_v03": SmallPolicyBeliefV03Buyer,
    "typed_belief": TypedBeliefBuyer,
    "typed_evidence_belief": TypedBeliefBuyer,
    "counterfactual_response_belief": CounterfactualResponseBeliefBuyer,
    "counterfactual_offer_model": CounterfactualResponseBeliefBuyer,
    "continuous_rule_ev": ContinuousRuleEVBuyer,
    "continual_rule_ev": ContinuousRuleEVBuyer,
    "continuous_rule_ev_current": ContinuousRuleEVBuyer,
    "continuous_rule_frozen_ev": ContinuousRuleFrozenEVBuyer,
    "continuous_rule_regime_monitor": ContinuousRuleRegimeMonitorBuyer,
    "continuous_rule_active_probe": ContinuousRuleActiveProbeBuyer,
    "continuous_rule_ev_conservative": ContinuousRuleConservativeEVBuyer,
    "continuous_rule_ev_cem": ContinuousRuleCEMEVBuyer,
    "continual_rule_ev_cem": ContinuousRuleCEMEVBuyer,
    "continuous_rule_ev_contextual_cem": ContinuousRuleContextualCEMEVBuyer,
    "continual_rule_ev_contextual_cem": ContinuousRuleContextualCEMEVBuyer,
    "continuous_hybrid_ev": ContinuousHybridEVBuyer,
    "continual_hybrid_ev": ContinuousHybridEVBuyer,
    "continuous_hybrid_prompt": ContinuousHybridPromptPlannerBuyer,
    "continual_hybrid_prompt": ContinuousHybridPromptPlannerBuyer,
    "bayesian_belief_llm_planner": BayesianBeliefLLMPlannerBuyer,
    "bayesian_posterior_llm_planner": BayesianBeliefLLMPlannerBuyer,
    "full_framework_bayesian_belief": BayesianBeliefLLMPlannerBuyer,
    "bayesian_belief_full_framework": BayesianBeliefFullFrameworkBuyer,
    "full_framework_bayesian_belief_only": BayesianBeliefFullFrameworkBuyer,
    "universal_framework_v1": UniversalFrameworkBuyer,
    "universal_framework_v1_frozen": UniversalFrameworkFrozenBuyer,
    "universal_framework_v1_wrong": UniversalFrameworkWrongBeliefBuyer,
    "universal_framework_v1_shuffled": UniversalFrameworkShuffledBeliefBuyer,
    "universal_framework_v1_oracle": UniversalFrameworkOracleBeliefBuyer,
    "universal_framework_v2": UniversalFrameworkV2Buyer,
    "universal_framework_v2_frozen": UniversalFrameworkV2FrozenBuyer,
    "universal_framework_v2_wrong": UniversalFrameworkV2WrongBeliefBuyer,
    "universal_framework_v2_shuffled": UniversalFrameworkV2ShuffledBeliefBuyer,
    "universal_framework_v2_oracle": UniversalFrameworkV2OracleBeliefBuyer,
    "universal_framework_v3": UniversalFrameworkV3Buyer,
    "universal_framework_v3_frozen": UniversalFrameworkV3FrozenBuyer,
    "universal_framework_v3_wrong": UniversalFrameworkV3WrongBeliefBuyer,
    "universal_framework_v3_shuffled": UniversalFrameworkV3ShuffledBeliefBuyer,
    "universal_framework_v3_oracle": UniversalFrameworkV3OracleBeliefBuyer,
    "universal_framework_v4": UniversalFrameworkV4Buyer,
    "universal_framework_v4_frozen": UniversalFrameworkV4FrozenBuyer,
    "universal_framework_v4_wrong_policy": UniversalFrameworkV4WrongPolicyBuyer,
    "universal_framework_v4_shuffled_full": UniversalFrameworkV4ShuffledFullBuyer,
    "universal_framework_v4_oracle_utility": UniversalFrameworkV4OracleUtilityBuyer,
    "universal_framework_v5": UniversalFrameworkV5Buyer,
    "universal_framework_v5_frozen": UniversalFrameworkV5FrozenBuyer,
    "universal_framework_v5_wrong_policy": UniversalFrameworkV5WrongPolicyBuyer,
    "universal_framework_v5_shuffled_full": UniversalFrameworkV5ShuffledFullBuyer,
    "universal_framework_v5_oracle_utility": UniversalFrameworkV5OracleUtilityBuyer,
    "universal_framework_v5_1": UniversalFrameworkV51Buyer,
    "universal_framework_v5_1_frozen": UniversalFrameworkV51FrozenBuyer,
    "universal_framework_v5_1_wrong_policy": UniversalFrameworkV51WrongPolicyBuyer,
    "universal_framework_v5_1_shuffled_full": UniversalFrameworkV51ShuffledFullBuyer,
    "universal_framework_v5_1_oracle_utility": UniversalFrameworkV51OracleUtilityBuyer,
    "universal_framework_v5_2": UniversalFrameworkV52Buyer,
    "universal_framework_v5_2_frozen": UniversalFrameworkV52FrozenBuyer,
    "universal_framework_v5_2_wrong_policy": UniversalFrameworkV52WrongPolicyBuyer,
    "universal_framework_v5_2_shuffled_full": UniversalFrameworkV52ShuffledFullBuyer,
    "universal_framework_v5_2_oracle_utility": UniversalFrameworkV52OracleUtilityBuyer,
    "universal_framework_v5_3": UniversalFrameworkV53Buyer,
    "universal_framework_v5_3_frozen": UniversalFrameworkV53FrozenBuyer,
    "universal_framework_v5_3_wrong_policy": UniversalFrameworkV53WrongPolicyBuyer,
    "universal_framework_v5_3_shuffled_full": UniversalFrameworkV53ShuffledFullBuyer,
    "universal_framework_v5_3_oracle_utility": UniversalFrameworkV53OracleUtilityBuyer,
    "universal_framework_v5_4": UniversalFrameworkV54Buyer,
    "universal_framework_v5_4_frozen": UniversalFrameworkV54FrozenBuyer,
    "universal_framework_v5_4_wrong_policy": UniversalFrameworkV54WrongPolicyBuyer,
    "universal_framework_v5_4_shuffled_full": UniversalFrameworkV54ShuffledFullBuyer,
    "universal_framework_v5_4_oracle_utility": UniversalFrameworkV54OracleUtilityBuyer,
    "universal_framework_v5_5": UniversalFrameworkV55Buyer,
    "universal_framework_v5_5_frozen": UniversalFrameworkV55FrozenBuyer,
    "universal_framework_v5_5_no_frontier": UniversalFrameworkV55NoFrontierBuyer,
    "universal_framework_v5_5_wrong_policy": UniversalFrameworkV55WrongPolicyBuyer,
    "universal_framework_v5_5_shuffled_full": UniversalFrameworkV55ShuffledFullBuyer,
    "universal_framework_v5_5_oracle_utility": UniversalFrameworkV55OracleUtilityBuyer,
    "universal_framework_v5_6": UniversalFrameworkV56Buyer,
    "universal_framework_v5_6_frozen": UniversalFrameworkV56FrozenBuyer,
    "universal_framework_v5_6_no_frontier": UniversalFrameworkV56NoFrontierBuyer,
    "universal_framework_v5_6_wrong_policy": UniversalFrameworkV56WrongPolicyBuyer,
    "universal_framework_v5_6_shuffled_full": UniversalFrameworkV56ShuffledFullBuyer,
    "universal_framework_v5_6_oracle_utility": UniversalFrameworkV56OracleUtilityBuyer,
    "universal_framework_v5_7": UniversalFrameworkV57Buyer,
    "universal_framework_v5_7_frozen": UniversalFrameworkV57FrozenBuyer,
    "universal_framework_v5_7_no_frontier": UniversalFrameworkV57NoFrontierBuyer,
    "universal_framework_v5_7_wrong_policy": UniversalFrameworkV57WrongPolicyBuyer,
    "universal_framework_v5_7_shuffled_full": UniversalFrameworkV57ShuffledFullBuyer,
    "universal_framework_v5_7_shuffled_mixture": UniversalFrameworkV57ShuffledMixtureBuyer,
    "universal_framework_v5_7_oracle_utility": UniversalFrameworkV57OracleUtilityBuyer,
    "universal_framework_v5_8": UniversalFrameworkV58Buyer,
    "universal_framework_v5_8_frozen": UniversalFrameworkV58FrozenBuyer,
    "universal_framework_v5_8_no_frontier": UniversalFrameworkV58NoFrontierBuyer,
    "universal_framework_v5_8_wrong_policy": UniversalFrameworkV58WrongPolicyBuyer,
    "universal_framework_v5_8_shuffled_full": UniversalFrameworkV58ShuffledFullBuyer,
    "universal_framework_v5_8_oracle_utility": UniversalFrameworkV58OracleUtilityBuyer,
    "universal_framework_v5_9": UniversalFrameworkV59Buyer,
    "universal_framework_v5_9_frozen": UniversalFrameworkV59FrozenBuyer,
    "universal_framework_v5_9_wrong_policy": UniversalFrameworkV59WrongPolicyBuyer,
    "universal_framework_v5_9_shuffled_mixture": UniversalFrameworkV59ShuffledMixtureBuyer,
    "universal_framework_v5_9_oracle_utility": UniversalFrameworkV59OracleUtilityBuyer,
    "universal_framework_v6_0": UniversalFrameworkV60Buyer,
    "universal_framework_v6_0_frozen": UniversalFrameworkV60FrozenBuyer,
    "universal_framework_v6_0_no_aspiration_planner": UniversalFrameworkV60NoAspirationPlannerBuyer,
    "universal_framework_v6_0_wrong_policy": UniversalFrameworkV60WrongPolicyBuyer,
    "universal_framework_v6_0_shuffled_mixture": UniversalFrameworkV60ShuffledMixtureBuyer,
    "universal_framework_v6_0_oracle_utility": UniversalFrameworkV60OracleUtilityBuyer,
    "universal_framework_v6_1": UniversalFrameworkV61Buyer,
    "universal_framework_v6_1_frozen": UniversalFrameworkV61FrozenBuyer,
    "universal_framework_v6_1_no_probe": UniversalFrameworkV61NoProbeBuyer,
    "universal_framework_v6_1_wrong_policy": UniversalFrameworkV61WrongPolicyBuyer,
    "universal_framework_v6_1_shuffled_mixture": UniversalFrameworkV61ShuffledMixtureBuyer,
    "universal_framework_v6_1_oracle_utility": UniversalFrameworkV61OracleUtilityBuyer,
    "universal_framework_v6_2_finetuned_planner": UniversalFrameworkV62FinetunedPlannerBuyer,
    "universal_framework_v6_2_finetuned_planner_unguarded": UniversalFrameworkV62UnguardedPlannerBuyer,
    "universal_framework_v6_3_conservative_awr": UniversalFrameworkV63ConservativeAWRBuyer,
    "universal_framework_v6_4_reward_labeled_lcb": UniversalFrameworkV64RewardLabeledLCBBuyer,
    "universal_framework_v6_5_evidence_gated_lcb": UniversalFrameworkV65EvidenceGatedLCBBuyer,
}


def make_buyer(
    variant: str,
    client: ModelClient,
    max_tokens: int,
    temperature: float,
    top_p: float,
    candidate_offer_k: int = 3,
    planner_client: ModelClient | None = None,
    continuous_planner_params_json: str | None = None,
):
    try:
        cls = BUYER_CLASSES[variant]
    except KeyError as exc:
        raise ValueError(f"Unknown Simple_Env buyer variant: {variant}. Available: {sorted(BUYER_CLASSES)}") from exc
    return cls(
        client=client,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        candidate_offer_k=candidate_offer_k,
        planner_client=planner_client,
        continuous_planner_params_json=continuous_planner_params_json,
    )
