"""Buyer variants supported by the modular AgenticPay wrapper.

The concrete AgenticPay agent classes live in
`experiments.agenticpay_framework` and the upstream AgenticPay repository. This
module keeps the experiment-facing registry small and explicit.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class BuyerVariantSpec:
    name: str
    family: str
    source: str
    description: str


BUYER_VARIANTS: Dict[str, BuyerVariantSpec] = {
    "repo_native": BuyerVariantSpec(
        name="repo_native",
        family="native",
        source="AgenticPay paper/repo native BuyerAgent",
        description="Original AgenticPay buyer prompt and behavior.",
    ),
    "direct_prompt": BuyerVariantSpec(
        name="direct_prompt",
        family="prompt",
        source="direct prompting baseline",
        description="Native buyer with a minimal direct bargaining reminder.",
    ),
    "cot_prompt": BuyerVariantSpec(
        name="cot_prompt",
        family="prompt",
        source="CoT / Pro-CoT-style baseline",
        description="Prompt-only baseline with private self-check reasoning.",
    ),
    "warm_prompt": BuyerVariantSpec(
        name="warm_prompt",
        family="prompt",
        source="style prompting baseline",
        description="Cooperative/warm bargaining style prompt.",
    ),
    "dominant_prompt": BuyerVariantSpec(
        name="dominant_prompt",
        family="prompt",
        source="style prompting / anchoring baseline",
        description="Firm/dominant anchoring style prompt.",
    ),
    "rule_offer_generator": BuyerVariantSpec(
        name="rule_offer_generator",
        family="planner",
        source="deterministic concession-schedule baseline",
        description="Rule offer planner plus native naturalizer/validator.",
    ),
    "astra_baseline": BuyerVariantSpec(
        name="astra_baseline",
        family="belief_planner",
        source="ASTRA-inspired belief + offer optimization",
        description="Belief estimate plus heuristic overlap offer optimizer.",
    ),
    "belief_prompt": BuyerVariantSpec(
        name="belief_prompt",
        family="our_ablation",
        source="our framework ablation",
        description="Opponent belief model injected into native buyer naturalizer.",
    ),
    "planner_generator": BuyerVariantSpec(
        name="planner_generator",
        family="our_ablation",
        source="our framework ablation",
        description="Strategic planner plus native language generator, without belief.",
    ),
    "full_framework": BuyerVariantSpec(
        name="full_framework",
        family="our_framework",
        source="our A+B+C framework",
        description="Belief model -> strategic planner -> naturalizer -> validator.",
    ),
    "universal_framework_v1": BuyerVariantSpec(
        name="universal_framework_v1",
        family="our_framework",
        source="cross-environment universal belief-usable planner",
        description="Persistent per-opponent belief, normalized candidate planner, action lock, and thin AgenticPay adapter.",
    ),
    "universal_framework_v1_frozen": BuyerVariantSpec(
        name="universal_framework_v1_frozen",
        family="our_ablation",
        source="universal framework causal control",
        description="Same planner and adapter with a frozen prior belief.",
    ),
    "universal_framework_v1_wrong": BuyerVariantSpec(
        name="universal_framework_v1_wrong",
        family="our_ablation",
        source="universal framework causal control",
        description="Same planner with a deliberately inverted high-confidence reservation belief.",
    ),
    "universal_framework_v1_shuffled": BuyerVariantSpec(
        name="universal_framework_v1_shuffled",
        family="our_ablation",
        source="universal framework causal control",
        description="Same planner with shuffled opponent preferences.",
    ),
    "universal_framework_v2_conservative_awr": BuyerVariantSpec(
        name="universal_framework_v2_conservative_awr",
        family="our_framework",
        source="cross-environment conservative offline RL / AWR",
        description="Bootstrap lower-confidence residual planner with repeated-opponent memory and safe base fallback.",
    ),
    "universal_framework_v3_action_consistent": BuyerVariantSpec(
        name="universal_framework_v3_action_consistent",
        family="our_framework",
        source="cross-environment framework protocol-correctness iteration 001",
        description="V1 belief/planner with deterministic action-aware rendering and semantic validation.",
    ),
    "universal_framework_v4_terminal_accept_guard": BuyerVariantSpec(
        name="universal_framework_v4_terminal_accept_guard",
        family="our_framework",
        source="cross-environment framework reward iteration 002",
        description="V3 plus a public-proposal-backed conservative terminal accept/continue boundary.",
    ),
    "universal_framework_v5_verified_response_frontier": BuyerVariantSpec(
        name="universal_framework_v5_verified_response_frontier",
        family="our_framework",
        source="cross-environment framework reward iteration 003",
        description="V4 plus a verified public-response frontier that avoids repeating formally rejected offers.",
    ),
    "universal_framework_v6_public_proposal_feasibility_guard": BuyerVariantSpec(
        name="universal_framework_v6_public_proposal_feasibility_guard",
        family="our_framework",
        source="cross-environment framework reward iteration 004",
        description="V5 plus an early exact-public-proposal feasibility guard using repeated public commitments.",
    ),
    "universal_framework_v7_action_locked_strategic_naturalization": BuyerVariantSpec(
        name="universal_framework_v7_action_locked_strategic_naturalization",
        family="our_framework",
        source="cross-environment framework reward iteration 006",
        description="Frozen V4 planner plus public-context strategic OFFER language under exact action/contract locking.",
    ),
    "universal_framework_v8_constrained_rhetorical_selector": BuyerVariantSpec(
        name="universal_framework_v8_constrained_rhetorical_selector",
        family="our_framework",
        source="cross-environment framework reward iteration 007",
        description="Frozen V4 planner plus an LLM-selected finite rhetorical act rendered by trusted templates.",
    ),
    "universal_framework_v9_llm_proposal_candidate": BuyerVariantSpec(
        name="universal_framework_v9_llm_proposal_candidate",
        family="our_framework",
        source="cross-environment framework reward iteration 008",
        description="Frozen V4 plus one public-only structured LLM proposal candidate under common planner arbitration and action locking.",
    ),
    "universal_framework_v10_belief_grounded_candidate_arbitrator": BuyerVariantSpec(
        name="universal_framework_v10_belief_grounded_candidate_arbitrator",
        family="our_framework",
        source="cross-environment framework reward iteration 009",
        description="V9 candidate pool plus a stalled-state belief-grounded constrained candidate-ID arbitrator.",
    ),
    "universal_framework_v11_safe_improvement_arbitrator": BuyerVariantSpec(
        name="universal_framework_v11_safe_improvement_arbitrator",
        family="our_framework",
        source="cross-environment framework reward iteration 010",
        description="V10 residual candidate suggestion gated by a frozen-reference score, utility, acceptance, and terminal-action trust region.",
    ),
    "universal_framework_v12_reward_labeled_residual_awr": BuyerVariantSpec(
        name="universal_framework_v12_reward_labeled_residual_awr",
        family="our_framework",
        source="cross-environment reward-labelled conservative offline RL / AWR iteration 011",
        description="Ensemble-LCB residual policy trained on official reward labels over the frozen V4 planner, with a local safe-improvement trust region.",
    ),
    "universal_framework_v13_reward_labeled_lcb": BuyerVariantSpec(
        name="universal_framework_v13_reward_labeled_lcb",
        family="our_framework",
        source="cross-environment reward-labelled conservative offline RL / AWR iteration 012",
        description="V12 with the conflicting hand-written trust region removed; retains the frozen V4 base, ensemble LCB, OOD penalty, initial-jump guard, and exact fallback.",
    ),
    "universal_framework_v14_evidence_gated_lcb": BuyerVariantSpec(
        name="universal_framework_v14_evidence_gated_lcb",
        family="our_framework",
        source="cross-environment reward-first iteration 013",
        description="V13 with a universal abstention rule that forbids residual overrides before any direct opponent response.",
    ),
    "universal_framework_v15_robust_contract_settlement_validator": BuyerVariantSpec(
        name="universal_framework_v15_robust_contract_settlement_validator",
        family="our_framework",
        source="cross-environment reward-first iteration 015",
        description="V13 plus a public-evidence hard validator that replaces terminal multi-issue ACCEPT with a buyer-IR robust settlement OFFER.",
    ),
    "universal_framework_v16_risk_adaptive_settlement_validator": BuyerVariantSpec(
        name="universal_framework_v16_risk_adaptive_settlement_validator",
        family="our_framework",
        source="cross-environment reward-first iteration 016",
        description="V13 plus a mandatory multi-issue settlement boundary whose buyer-IR repair margin grows with public proposal staleness.",
    ),
    "universal_framework_v17_validated_calibrated_opening": BuyerVariantSpec(
        name="universal_framework_v17_validated_calibrated_opening",
        family="our_framework",
        source="cross-environment reward-first iteration 017",
        description="V16 plus a schema- and buyer-IR-validated LLM term profile with a trusted utility-reserve price for the first contract action only.",
    ),
    "universal_framework_v18_public_counteroffer_term_validator": BuyerVariantSpec(
        name="universal_framework_v18_public_counteroffer_term_validator",
        family="our_framework",
        source="cross-environment reward-first iteration 018",
        description="V17 plus a public-evidence validator that ends opening after the first seller offer and aligns repeated, price-converged counteroffer terms when buyer-IR.",
    ),
    "universal_framework_v19_minimal_buyer_ir_term_repair": BuyerVariantSpec(
        name="universal_framework_v19_minimal_buyer_ir_term_repair",
        family="our_framework",
        source="cross-environment reward-first iteration 019",
        description="V17 plus a trusted minimal-deviation repair from repeated seller terms to a buyer-IR contract, with public-staleness price incentive.",
    ),
    "universal_framework_v20_semantic_low_burden_endpoint_opening": BuyerVariantSpec(
        name="universal_framework_v20_semantic_low_burden_endpoint_opening",
        family="our_framework",
        source="cross-environment reward-first iteration 020",
        description="V19 plus a public-semantics opening rule that maps every continuous service obligation to a seller-low-burden legal endpoint before trusted buyer-IR price calibration.",
    ),
    "universal_framework_v21_public_only_burden_selector": BuyerVariantSpec(
        name="universal_framework_v21_public_only_burden_selector",
        family="our_framework",
        source="cross-environment reward-first iteration 021",
        description="V20 with an information firewall: semantic term selection sees only public product/schema meanings, while buyer utility remains private to trusted IR and price validation.",
    ),
    "universal_framework_v25_classifier_composed_opening": BuyerVariantSpec(
        name="universal_framework_v25_classifier_composed_opening",
        family="our_framework",
        source="cross-environment reward-first iteration 025",
        description="V17 planner with a separately audited ontological/option-rating issue classifier and trusted buyer-IR price-only opening composer.",
    ),
    "universal_framework_v26_rejectable_classifier_guard": BuyerVariantSpec(
        name="universal_framework_v26_rejectable_classifier_guard",
        family="our_framework",
        source="cross-environment reward-first iteration 026",
        description="V25 plus a cross-turn abstention-aware semantic guard: unsupported term inversions are blocked, while complete seller counteroffers can reject the semantic prior as stronger direct evidence.",
    ),
    "universal_framework_v27_classifier_guard_buffer_1pct": BuyerVariantSpec(
        name="universal_framework_v27_classifier_guard_buffer_1pct",
        family="our_framework",
        source="cross-environment reward-first iteration 027",
        description="V26 plus a buyer-cushion-capped 1% public-contract settlement uncertainty buffer before terminal acceptance.",
    ),
    "universal_framework_v28_classifier_guard_buffer_2pct": BuyerVariantSpec(
        name="universal_framework_v28_classifier_guard_buffer_2pct",
        family="our_framework",
        source="cross-environment reward-first iteration 028",
        description="V26 plus a buyer-cushion-capped 2% public-contract settlement uncertainty buffer for an automatic risk/reward comparison with V27.",
    ),
    "universal_framework_v29_semantic_risk_settlement": BuyerVariantSpec(
        name="universal_framework_v29_semantic_risk_settlement",
        family="our_framework",
        source="cross-environment reward-first iteration 029",
        description="V27 with the conflicting legacy minimal buyer-IR term repair removed and a utility-weight-free settlement buffer scaled by public semantic departure from the high-confidence classifier profile.",
    ),
    "universal_framework_v30_evidence_gated_settlement_frontier": BuyerVariantSpec(
        name="universal_framework_v30_evidence_gated_settlement_frontier",
        family="our_framework",
        source="cross-environment reward-first iteration 030",
        description="V29 plus an evidence-gated multi-issue settlement frontier: compensated buyer-utility probes are one-shot and rejectable, explicit public acceptance is latched, and seller-term-matching offers cannot bypass the semantic-risk price floor.",
    ),
    "universal_framework_v31_bounded_compensated_active_frontier": BuyerVariantSpec(
        name="universal_framework_v31_bounded_compensated_active_frontier",
        family="our_framework",
        source="cross-environment reward-first iteration 031",
        description="V30 with a buyer-side utility-leverage safety gate, midpoint continuous probes, grounded compensation rhetoric, and a base-only floor for ordinary counteroffers while semantic risk remains a terminal-settlement constraint.",
    ),
    "universal_framework_v32_noncrossing_single_issue_frontier": BuyerVariantSpec(
        name="universal_framework_v32_noncrossing_single_issue_frontier",
        family="our_framework",
        source="cross-environment reward-first iteration 032",
        description="V31 with a one-shot, one-issue, strictly non-crossing information probe; seller-term settlement again uses the full public semantic-risk buffer.",
    ),
    "universal_framework_v33_public_response_settlement_latch": BuyerVariantSpec(
        name="universal_framework_v33_public_response_settlement_latch",
        family="our_framework",
        source="cross-environment reward-first iteration 033",
        description="V32 plus grounded explicit-acceptance parsing and a buyer-IR public-counter settlement latch immediately after an information probe.",
    ),
    "universal_framework_v34_post_probe_minimal_buyer_ir_repair": BuyerVariantSpec(
        name="universal_framework_v34_post_probe_minimal_buyer_ir_repair",
        family="our_framework",
        source="cross-environment reward-first iteration 034",
        description="V33 plus a one-shot, same-price, one-field minimum repair when the immediate complete post-probe seller counter is just outside buyer IR.",
    ),
    "universal_framework_v35_domain_aware_post_probe_repair": BuyerVariantSpec(
        name="universal_framework_v35_domain_aware_post_probe_repair",
        family="our_framework",
        source="cross-environment reward-first iteration 035",
        description="V34 with natural-unit quantization for count-like continuous issues, rounding only toward the buyer-favorable endpoint so the repaired offer remains buyer-IR and human-interpretable.",
    ),
    "universal_framework_v36_publicly_compensated_post_probe_repair": BuyerVariantSpec(
        name="universal_framework_v36_publicly_compensated_post_probe_repair",
        family="our_framework",
        source="cross-environment reward-first iteration 036",
        description="V35 plus a one-shot cent-quantized price compensation funded only by buyer utility above the 1% reserve, triggered only when the seller publicly rejects the repair and explicitly requests compensation.",
    ),
    "universal_framework_v37_rolling_public_contract_state": BuyerVariantSpec(
        name="universal_framework_v37_rolling_public_contract_state",
        family="our_framework",
        source="cross-environment reward-first iteration 037",
        description="V36 with a rolling latest-public-counter state machine: structured seller counters override ambiguous acceptance prose, stale anchors are invalidated, and exact latch actions are replayed at most once.",
    ),
    "universal_framework_v38_utility_preserving_multiissue": BuyerVariantSpec(
        name="universal_framework_v38_utility_preserving_multiissue",
        family="our_framework",
        source="cross-environment reward-first iteration 038",
        description="V37 plus buyer-utility-bounded semantic openings and a deadline-aware Pareto-safe public-counter validator that changes at most one issue without reading seller-private utility.",
    ),
    "universal_framework_v39_confirmed_tradeoff_settlement": BuyerVariantSpec(
        name="universal_framework_v39_confirmed_tradeoff_settlement",
        family="our_framework",
        source="cross-environment reward-first iteration 039",
        description="V38 narrowed to one protected opening issue, with a semantic-departure terminal gate and one-issue burden/price tradeoff confirmation before high-risk settlement.",
    ),
    "universal_framework_v40_stagnation_trade_ledger": BuyerVariantSpec(
        name="universal_framework_v40_stagnation_trade_ledger",
        family="our_framework",
        source="cross-environment reward-first iteration 040",
        description="V37 plus a deadlock-only public trade ledger: after three exact seller-contract repeats, match the stated seller price and change the minimum buyer-known fields needed for a 5% buyer-IR reserve.",
    ),
    "universal_framework_v41_compensated_conflict_opening": BuyerVariantSpec(
        name="universal_framework_v41_compensated_conflict_opening",
        family="our_framework",
        source="cross-environment reward-first iteration 041",
        description="Frozen V37 plus an opt-in, buyer-IR-gated high-conflict opening: a bounded buyer-term projection is exposed only when the public base ceiling can fully price-compensate it without using seller-private utility.",
    ),
    "universal_framework_v42_sequential_semantic_confirmation": BuyerVariantSpec(
        name="universal_framework_v42_sequential_semantic_confirmation",
        family="our_framework",
        source="cross-environment reward-first iteration 042",
        description="V41 plus a mandatory same-price, one-issue confirmation step for undercompensated public counters that strongly depart from the low-burden semantic profile.",
    ),
    "universal_framework_v43_raw_semantic_confirmation": BuyerVariantSpec(
        name="universal_framework_v43_raw_semantic_confirmation",
        family="our_framework",
        source="cross-environment reward-first iteration 043",
        description="V42 with explicit dual profile state: raw low-burden semantics diagnose provider-side departure, while the projected profile remains solely a buyer-safe action constructor.",
    ),
    "universal_framework_v44_risk_budgeted_confirmation": BuyerVariantSpec(
        name="universal_framework_v44_risk_budgeted_confirmation",
        family="our_framework",
        source="cross-environment reward-first iteration 044",
        description="V41 plus a raw-profile risk-budgeted repair that changes the minimum buyer-cost issue set and stays strictly below the seller price until a real response is observed.",
    ),
    "universal_framework_v45_rejection_tightened_confirmation": BuyerVariantSpec(
        name="universal_framework_v45_rejection_tightened_confirmation",
        family="our_framework",
        source="cross-environment reward-first iteration 045",
        description="V44 plus a public-rejection transition: if the seller restores a high-risk package after confirmation, tighten the next semantic-risk budget to zero while remaining non-crossing and buyer-IR.",
    ),
    "universal_framework_v46_ordinal_burden_frontier": BuyerVariantSpec(
        name="universal_framework_v46_ordinal_burden_frontier",
        family="our_framework",
        source="cross-environment reward-first iteration 046",
        description="V45 plus an ordinal public-burden frontier: after rejection, enumerate legal options and choose the lowest classifier-ranked burden package that remains buyer-IR and strictly non-crossing.",
    ),
    "universal_framework_v47_ir_gated_ordinal_frontier": BuyerVariantSpec(
        name="universal_framework_v47_ir_gated_ordinal_frontier",
        family="our_framework",
        source="cross-environment reward-first iteration 047",
        description="V46 narrowed by a trusted buyer-side gate: ordinal intermediate options are explored only when the raw minimum-burden endpoint is outside the 5% buyer-IR reserve; otherwise behavior falls back to V44.",
    ),
    "universal_framework_v48_rejection_aware_ordinal_frontier": BuyerVariantSpec(
        name="universal_framework_v48_rejection_aware_ordinal_frontier",
        family="our_framework",
        source="cross-environment reward-first iteration 048",
        description="V47 plus public rejection constraints: any issue value explicitly restored by a seller counter is frozen to the latest seller value, so ordinal search explores only untested fields.",
    ),
    "universal_framework_v49_genuine_intermediate_frontier": BuyerVariantSpec(
        name="universal_framework_v49_genuine_intermediate_frontier",
        family="our_framework",
        source="cross-environment reward-first iteration 049",
        description="V48 narrowed to genuine ordinal interpolation: only options whose classifier burden lies strictly between the seller's current value and the raw argmin may change; binary endpoint flips are excluded.",
    ),
    "universal_framework_v50_one_shot_confirmation": BuyerVariantSpec(
        name="universal_framework_v50_one_shot_confirmation",
        family="our_framework",
        source="cross-environment reward-first iteration 050",
        description="V44 with an explicit probe lifecycle: at most one risk-budgeted semantic confirmation may be selected per episode; after its public response, control returns to the frozen V37 rolling planner.",
    ),
    "universal_framework_v51_v37_isolated_one_shot_probe": BuyerVariantSpec(
        name="universal_framework_v51_v37_isolated_one_shot_probe",
        family="our_framework",
        source="cross-environment reward-first iteration 051",
        description="Frozen V37 plus only the one-shot risk-budgeted confirmation probe; V41 compensated-conflict opening and all V45-V49 post-rejection heuristics remain disabled.",
    ),
    "universal_framework_v52_learned_issue_role_gate": BuyerVariantSpec(
        name="universal_framework_v52_learned_issue_role_gate",
        family="our_framework",
        source="cross-environment reward-first iteration 052",
        description="Frozen V37 plus a checkpointed rejectable public issue-role gate that prevents descriptive/evidence-grounded fields from entering provider-burden optimization.",
    ),
    "universal_framework_v53_public_factual_router": BuyerVariantSpec(
        name="universal_framework_v53_public_factual_router",
        family="our_framework",
        source="cross-environment reward-first iteration 053",
        description="V52 role routing plus an independent, consensus-and-abstention public factual classifier for descriptive issue values; uncertain evidence uses an explicit uncertainty option rather than the buyer-preferred label.",
    ),
    "universal_framework_v54_role_conditioned_partner_ir_reserve": BuyerVariantSpec(
        name="universal_framework_v54_role_conditioned_partner_ir_reserve",
        family="our_framework",
        source="cross-environment reward-first iteration 055",
        description="V53 plus a bounded pre-commit reserve conditioned on public semantic departure and non-abstained operational issue roles; it never reads seller-private utility and preserves buyer IR.",
    ),
    "universal_framework_v55_multiseller_protocol_safe": BuyerVariantSpec(
        name="universal_framework_v55_multiseller_protocol_safe",
        family="our_framework",
        source="cross-environment protocol-correctness iteration 056",
        description="Frozen V37 planner with seller-scoped routing, buyer-visible per-seller contract adaptation, complete-contract rendering, and fail-closed route/schema/action validation.",
    ),
    "universal_framework_v56_deadline_aware_settlement": BuyerVariantSpec(
        name="universal_framework_v56_deadline_aware_settlement",
        family="our_framework",
        source="cross-environment strategy iteration 057",
        description="V55 protocol-safe adapter plus a public-stagnation/deadline gate that suppresses repeated low offers or quit and selects the highest-readiness candidate under a decaying buyer-IR reserve.",
    ),
    "universal_framework_v57_stagnation_financed_settlement": BuyerVariantSpec(
        name="universal_framework_v57_stagnation_financed_settlement",
        family="our_framework",
        source="cross-environment strategy iteration 058",
        description="V56 plus a public trade-ledger candidate that matches a repeated seller price and funds it with the minimum buyer-value term repair needed to retain a decaying buyer-IR reserve.",
    ),
    "universal_framework_v58_rejection_aware_settlement": BuyerVariantSpec(
        name="universal_framework_v58_rejection_aware_settlement",
        family="our_framework",
        source="cross-environment strategy iteration 059",
        description="V57 plus behavioral issue rejection: a seller counter that restores a changed field freezes that field, and the next financed settlement tries the next-lowest buyer-cost legal repair.",
    ),
    "universal_framework_v59_scoped_rejection_settlement": BuyerVariantSpec(
        name="universal_framework_v59_scoped_rejection_settlement",
        family="our_framework",
        source="cross-environment strategy iteration 060",
        description="V58 with precision-scoped rejection extraction: only a seller counter immediately following a marked trade-ledger repair freezes changed issues; ordinary opening counters remain negotiable.",
    ),
    "universal_framework_v60_resilient_multiseller_settlement": BuyerVariantSpec(
        name="universal_framework_v60_resilient_multiseller_settlement",
        family="our_framework",
        source="cross-environment multi-seller strategy iteration 061",
        description="V59 plus bounded retry of seller edges whose response contains no valid public contract, followed by routing solely on buyer utility of public contracts; seller-private utility is never used.",
    ),
}


DEFAULT_BASELINES: List[str] = [
    "repo_native",
    "direct_prompt",
    "cot_prompt",
    "rule_offer_generator",
    "astra_baseline",
    "belief_prompt",
    "planner_generator",
    "full_framework",
    "universal_framework_v1",
]

FRAMEWORK_VARIANTS: List[str] = [
    "belief_prompt",
    "planner_generator",
    "full_framework",
    "universal_framework_v1",
    "universal_framework_v1_frozen",
    "universal_framework_v1_wrong",
    "universal_framework_v1_shuffled",
    "universal_framework_v2_conservative_awr",
    "universal_framework_v3_action_consistent",
    "universal_framework_v4_terminal_accept_guard",
    "universal_framework_v5_verified_response_frontier",
    "universal_framework_v6_public_proposal_feasibility_guard",
    "universal_framework_v7_action_locked_strategic_naturalization",
    "universal_framework_v8_constrained_rhetorical_selector",
    "universal_framework_v9_llm_proposal_candidate",
    "universal_framework_v10_belief_grounded_candidate_arbitrator",
    "universal_framework_v11_safe_improvement_arbitrator",
    "universal_framework_v12_reward_labeled_residual_awr",
    "universal_framework_v13_reward_labeled_lcb",
    "universal_framework_v14_evidence_gated_lcb",
    "universal_framework_v15_robust_contract_settlement_validator",
    "universal_framework_v16_risk_adaptive_settlement_validator",
    "universal_framework_v17_validated_calibrated_opening",
    "universal_framework_v18_public_counteroffer_term_validator",
    "universal_framework_v19_minimal_buyer_ir_term_repair",
    "universal_framework_v20_semantic_low_burden_endpoint_opening",
    "universal_framework_v21_public_only_burden_selector",
    "universal_framework_v25_classifier_composed_opening",
    "universal_framework_v26_rejectable_classifier_guard",
    "universal_framework_v27_classifier_guard_buffer_1pct",
    "universal_framework_v28_classifier_guard_buffer_2pct",
    "universal_framework_v29_semantic_risk_settlement",
    "universal_framework_v30_evidence_gated_settlement_frontier",
    "universal_framework_v31_bounded_compensated_active_frontier",
    "universal_framework_v32_noncrossing_single_issue_frontier",
    "universal_framework_v33_public_response_settlement_latch",
    "universal_framework_v34_post_probe_minimal_buyer_ir_repair",
    "universal_framework_v35_domain_aware_post_probe_repair",
    "universal_framework_v36_publicly_compensated_post_probe_repair",
    "universal_framework_v37_rolling_public_contract_state",
    "universal_framework_v38_utility_preserving_multiissue",
    "universal_framework_v39_confirmed_tradeoff_settlement",
    "universal_framework_v40_stagnation_trade_ledger",
    "universal_framework_v41_compensated_conflict_opening",
    "universal_framework_v42_sequential_semantic_confirmation",
    "universal_framework_v43_raw_semantic_confirmation",
    "universal_framework_v44_risk_budgeted_confirmation",
    "universal_framework_v45_rejection_tightened_confirmation",
    "universal_framework_v46_ordinal_burden_frontier",
    "universal_framework_v47_ir_gated_ordinal_frontier",
    "universal_framework_v48_rejection_aware_ordinal_frontier",
    "universal_framework_v49_genuine_intermediate_frontier",
    "universal_framework_v50_one_shot_confirmation",
    "universal_framework_v51_v37_isolated_one_shot_probe",
    "universal_framework_v52_learned_issue_role_gate",
    "universal_framework_v53_public_factual_router",
    "universal_framework_v54_role_conditioned_partner_ir_reserve",
    "universal_framework_v55_multiseller_protocol_safe",
    "universal_framework_v56_deadline_aware_settlement",
    "universal_framework_v57_stagnation_financed_settlement",
    "universal_framework_v58_rejection_aware_settlement",
    "universal_framework_v59_scoped_rejection_settlement",
    "universal_framework_v60_resilient_multiseller_settlement",
]


def universal_belief_mode(variant: str) -> str | None:
    return {
        "universal_framework_v1": "learned",
        "universal_framework_v1_frozen": "frozen",
        "universal_framework_v1_wrong": "wrong",
        "universal_framework_v1_shuffled": "shuffled",
        "universal_framework_v2_conservative_awr": "learned",
        "universal_framework_v3_action_consistent": "learned",
        "universal_framework_v4_terminal_accept_guard": "learned",
        "universal_framework_v5_verified_response_frontier": "learned",
        "universal_framework_v6_public_proposal_feasibility_guard": "learned",
        "universal_framework_v7_action_locked_strategic_naturalization": "learned",
        "universal_framework_v8_constrained_rhetorical_selector": "learned",
        "universal_framework_v9_llm_proposal_candidate": "learned",
        "universal_framework_v10_belief_grounded_candidate_arbitrator": "learned",
        "universal_framework_v11_safe_improvement_arbitrator": "learned",
        "universal_framework_v12_reward_labeled_residual_awr": "learned",
        "universal_framework_v13_reward_labeled_lcb": "learned",
        "universal_framework_v14_evidence_gated_lcb": "learned",
        "universal_framework_v15_robust_contract_settlement_validator": "learned",
        "universal_framework_v16_risk_adaptive_settlement_validator": "learned",
        "universal_framework_v17_validated_calibrated_opening": "learned",
        "universal_framework_v18_public_counteroffer_term_validator": "learned",
        "universal_framework_v19_minimal_buyer_ir_term_repair": "learned",
        "universal_framework_v20_semantic_low_burden_endpoint_opening": "learned",
        "universal_framework_v21_public_only_burden_selector": "learned",
        "universal_framework_v25_classifier_composed_opening": "learned",
        "universal_framework_v26_rejectable_classifier_guard": "learned",
        "universal_framework_v27_classifier_guard_buffer_1pct": "learned",
        "universal_framework_v28_classifier_guard_buffer_2pct": "learned",
        "universal_framework_v29_semantic_risk_settlement": "learned",
        "universal_framework_v30_evidence_gated_settlement_frontier": "learned",
        "universal_framework_v31_bounded_compensated_active_frontier": "learned",
        "universal_framework_v32_noncrossing_single_issue_frontier": "learned",
        "universal_framework_v33_public_response_settlement_latch": "learned",
        "universal_framework_v34_post_probe_minimal_buyer_ir_repair": "learned",
        "universal_framework_v35_domain_aware_post_probe_repair": "learned",
        "universal_framework_v36_publicly_compensated_post_probe_repair": "learned",
        "universal_framework_v37_rolling_public_contract_state": "learned",
        "universal_framework_v38_utility_preserving_multiissue": "learned",
        "universal_framework_v39_confirmed_tradeoff_settlement": "learned",
        "universal_framework_v40_stagnation_trade_ledger": "learned",
        "universal_framework_v41_compensated_conflict_opening": "learned",
        "universal_framework_v42_sequential_semantic_confirmation": "learned",
        "universal_framework_v43_raw_semantic_confirmation": "learned",
        "universal_framework_v44_risk_budgeted_confirmation": "learned",
        "universal_framework_v45_rejection_tightened_confirmation": "learned",
        "universal_framework_v46_ordinal_burden_frontier": "learned",
        "universal_framework_v47_ir_gated_ordinal_frontier": "learned",
        "universal_framework_v48_rejection_aware_ordinal_frontier": "learned",
        "universal_framework_v49_genuine_intermediate_frontier": "learned",
        "universal_framework_v50_one_shot_confirmation": "learned",
        "universal_framework_v51_v37_isolated_one_shot_probe": "learned",
        "universal_framework_v52_learned_issue_role_gate": "learned",
        "universal_framework_v53_public_factual_router": "learned",
        "universal_framework_v54_role_conditioned_partner_ir_reserve": "learned",
        "universal_framework_v55_multiseller_protocol_safe": "learned",
        "universal_framework_v56_deadline_aware_settlement": "learned",
        "universal_framework_v57_stagnation_financed_settlement": "learned",
        "universal_framework_v58_rejection_aware_settlement": "learned",
        "universal_framework_v59_scoped_rejection_settlement": "learned",
        "universal_framework_v60_resilient_multiseller_settlement": "learned",
    }.get(variant)


def parse_buyer_variants(raw: str | None) -> List[str]:
    if not raw or raw.strip().lower() in {"default", "all"}:
        return list(DEFAULT_BASELINES)
    variants = [item.strip() for item in raw.split(",") if item.strip()]
    unknown = sorted(set(variants) - set(BUYER_VARIANTS))
    if unknown:
        raise ValueError(f"Unknown AgenticPay buyer variants: {unknown}. Available: {sorted(BUYER_VARIANTS)}")
    return variants
